AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Sample
      CodeUri: lambdas/sample/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints: 
        - app.ts
        External:
        - better-sqlite3
        - mysql2
        - pg-query-stream
        - oracledb
        - sqlite3
        - tedious
        - mysql
        - pg-native

Outputs:
  SampleFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleFunction.Arn
  SampleFunctionIamRole:
    Description: "Implicit IAM Role created for Sample function"
    Value: !GetAtt SampleFunction.Arn
